"""empty message

Revision ID: 43c1a8d2abcc
Revises: 8ce7a70dda93
Create Date: 2023-11-18 11:21:26.195641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c1a8d2abcc'
down_revision = '8ce7a70dda93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_view', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###
