"""empty message

Revision ID: 8ce7a70dda93
Revises: 
Create Date: 2023-11-18 10:30:02.266532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce7a70dda93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_energy', sa.String(length=255), nullable=True),
    sa.Column('period_day_correct', sa.Boolean(), nullable=True),
    sa.Column('period_day_set', sa.Integer(), nullable=True),
    sa.Column('training_type', sa.String(length=255), nullable=True),
    sa.Column('feedback', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_view')
    # ### end Alembic commands ###
